//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoping {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]

        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("shoping.query", typeof(query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=171,Y=17}.
        /// </summary>
        internal static System.Drawing.Point advanceDataSet_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("advanceDataSet.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool bindingNavigator1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("bindingNavigator1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point bindingNavigator1_Location {
            get {
                object obj = ResourceManager.GetObject("bindingNavigator1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=712, Height=36}.
        /// </summary>
        internal static System.Drawing.Size bindingNavigator1_Size {
            get {
                object obj = ResourceManager.GetObject("bindingNavigator1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 33.
        /// </summary>
        internal static int bindingNavigator1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("bindingNavigator1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bindingNavigator1.
        /// </summary>
        internal static string bindingNavigator1_Text {
            get {
                return ResourceManager.GetString("bindingNavigator1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point bindingNavigator1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("bindingNavigator1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=36, Height=33}.
        /// </summary>
        internal static System.Drawing.Size bindingNavigatorCountItem_Size {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorCountItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من{0}.
        /// </summary>
        internal static string bindingNavigatorCountItem_Text {
            get {
                return ResourceManager.GetString("bindingNavigatorCountItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of items.
        /// </summary>
        internal static string bindingNavigatorCountItem_ToolTipText {
            get {
                return ResourceManager.GetString("bindingNavigatorCountItem.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bindingNavigatorMoveFirstItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveFirstItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool bindingNavigatorMoveFirstItem_RightToLeftAutoMirrorImage {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=23, Height=33}.
        /// </summary>
        internal static System.Drawing.Size bindingNavigatorMoveFirstItem_Size {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveFirstItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        internal static string bindingNavigatorMoveFirstItem_Text {
            get {
                return ResourceManager.GetString("bindingNavigatorMoveFirstItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bindingNavigatorMoveLastItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveLastItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool bindingNavigatorMoveLastItem_RightToLeftAutoMirrorImage {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=23, Height=33}.
        /// </summary>
        internal static System.Drawing.Size bindingNavigatorMoveLastItem_Size {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveLastItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move last.
        /// </summary>
        internal static string bindingNavigatorMoveLastItem_Text {
            get {
                return ResourceManager.GetString("bindingNavigatorMoveLastItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bindingNavigatorMoveNextItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveNextItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool bindingNavigatorMoveNextItem_RightToLeftAutoMirrorImage {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=23, Height=33}.
        /// </summary>
        internal static System.Drawing.Size bindingNavigatorMoveNextItem_Size {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMoveNextItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        internal static string bindingNavigatorMoveNextItem_Text {
            get {
                return ResourceManager.GetString("bindingNavigatorMoveNextItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bindingNavigatorMovePreviousItem_Image {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMovePreviousItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool bindingNavigatorMovePreviousItem_RightToLeftAutoMirrorImage {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=23, Height=33}.
        /// </summary>
        internal static System.Drawing.Size bindingNavigatorMovePreviousItem_Size {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorMovePreviousItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        internal static string bindingNavigatorMovePreviousItem_Text {
            get {
                return ResourceManager.GetString("bindingNavigatorMovePreviousItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string bindingNavigatorPositionItem_AccessibleName {
            get {
                return ResourceManager.GetString("bindingNavigatorPositionItem.AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool bindingNavigatorPositionItem_AutoSize {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorPositionItem.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=50, Height=23}.
        /// </summary>
        internal static System.Drawing.Size bindingNavigatorPositionItem_Size {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorPositionItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string bindingNavigatorPositionItem_Text {
            get {
                return ResourceManager.GetString("bindingNavigatorPositionItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position.
        /// </summary>
        internal static string bindingNavigatorPositionItem_ToolTipText {
            get {
                return ResourceManager.GetString("bindingNavigatorPositionItem.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=36}.
        /// </summary>
        internal static System.Drawing.Size bindingNavigatorSeparator_Size {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorSeparator.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=36}.
        /// </summary>
        internal static System.Drawing.Size bindingNavigatorSeparator1_Size {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorSeparator1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=36}.
        /// </summary>
        internal static System.Drawing.Size bindingNavigatorSeparator2_Size {
            get {
                object obj = ResourceManager.GetObject("bindingNavigatorSeparator2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool cruncy_AutoSize {
            get {
                object obj = ResourceManager.GetObject("cruncy.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font cruncy_Font {
            get {
                object obj = ResourceManager.GetObject("cruncy.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=271,Y=257}.
        /// </summary>
        internal static System.Drawing.Point cruncy_Location {
            get {
                object obj = ResourceManager.GetObject("cruncy.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=37, Height=31}.
        /// </summary>
        internal static System.Drawing.Size cruncy_Size {
            get {
                object obj = ResourceManager.GetObject("cruncy.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 28.
        /// </summary>
        internal static int cruncy_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cruncy.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ريال.
        /// </summary>
        internal static string cruncy_Text {
            get {
                return ResourceManager.GetString("cruncy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool cruncy_Visible {
            get {
                object obj = ResourceManager.GetObject("cruncy.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool custom_idLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("custom_idLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font custom_idLabel_Font {
            get {
                object obj = ResourceManager.GetObject("custom_idLabel.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool custom_idLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("custom_idLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=8,Y=108}.
        /// </summary>
        internal static System.Drawing.Point custom_idLabel_Location {
            get {
                object obj = ResourceManager.GetObject("custom_idLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=82, Height=31}.
        /// </summary>
        internal static System.Drawing.Size custom_idLabel_Size {
            get {
                object obj = ResourceManager.GetObject("custom_idLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 19.
        /// </summary>
        internal static int custom_idLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("custom_idLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب.
        /// </summary>
        internal static string custom_idLabel_Text {
            get {
                return ResourceManager.GetString("custom_idLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font custom_idTextBox_Font {
            get {
                object obj = ResourceManager.GetObject("custom_idTextBox.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=139}.
        /// </summary>
        internal static System.Drawing.Point custom_idTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("custom_idTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=4,Right=3,Bottom=4}.
        /// </summary>
        internal static System.Windows.Forms.Padding custom_idTextBox_Margin {
            get {
                object obj = ResourceManager.GetObject("custom_idTextBox.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool custom_idTextBox_Multiline {
            get {
                object obj = ResourceManager.GetObject("custom_idTextBox.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=103, Height=34}.
        /// </summary>
        internal static System.Drawing.Size custom_idTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("custom_idTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 20.
        /// </summary>
        internal static int custom_idTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("custom_idTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.HorizontalAlignment similar to Center.
        /// </summary>
        internal static System.Windows.Forms.HorizontalAlignment custom_idTextBox_TextAlign {
            get {
                object obj = ResourceManager.GetObject("custom_idTextBox.TextAlign", resourceCulture);
                return ((System.Windows.Forms.HorizontalAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool custom_nameLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("custom_nameLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font custom_nameLabel_Font {
            get {
                object obj = ResourceManager.GetObject("custom_nameLabel.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool custom_nameLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("custom_nameLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=122,Y=147}.
        /// </summary>
        internal static System.Drawing.Point custom_nameLabel_Location {
            get {
                object obj = ResourceManager.GetObject("custom_nameLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=91, Height=31}.
        /// </summary>
        internal static System.Drawing.Size custom_nameLabel_Size {
            get {
                object obj = ResourceManager.GetObject("custom_nameLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 21.
        /// </summary>
        internal static int custom_nameLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("custom_nameLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        internal static string custom_nameLabel_Text {
            get {
                return ResourceManager.GetString("custom_nameLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font custom_nameTextBox_Font {
            get {
                object obj = ResourceManager.GetObject("custom_nameTextBox.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=128,Y=177}.
        /// </summary>
        internal static System.Drawing.Point custom_nameTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("custom_nameTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=4,Right=3,Bottom=4}.
        /// </summary>
        internal static System.Windows.Forms.Padding custom_nameTextBox_Margin {
            get {
                object obj = ResourceManager.GetObject("custom_nameTextBox.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool custom_nameTextBox_Multiline {
            get {
                object obj = ResourceManager.GetObject("custom_nameTextBox.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=263, Height=35}.
        /// </summary>
        internal static System.Drawing.Size custom_nameTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("custom_nameTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 22.
        /// </summary>
        internal static int custom_nameTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("custom_nameTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.HorizontalAlignment similar to Center.
        /// </summary>
        internal static System.Windows.Forms.HorizontalAlignment custom_nameTextBox_TextAlign {
            get {
                object obj = ResourceManager.GetObject("custom_nameTextBox.TextAlign", resourceCulture);
                return ((System.Windows.Forms.HorizontalAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool end_totalLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("end_totalLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font end_totalLabel_Font {
            get {
                object obj = ResourceManager.GetObject("end_totalLabel.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool end_totalLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("end_totalLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=122,Y=222}.
        /// </summary>
        internal static System.Drawing.Point end_totalLabel_Location {
            get {
                object obj = ResourceManager.GetObject("end_totalLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=150, Height=31}.
        /// </summary>
        internal static System.Drawing.Size end_totalLabel_Size {
            get {
                object obj = ResourceManager.GetObject("end_totalLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 23.
        /// </summary>
        internal static int end_totalLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("end_totalLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الحساب المتبقي.
        /// </summary>
        internal static string end_totalLabel_Text {
            get {
                return ResourceManager.GetString("end_totalLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font end_totalTextBox_Font {
            get {
                object obj = ResourceManager.GetObject("end_totalTextBox.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=125,Y=252}.
        /// </summary>
        internal static System.Drawing.Point end_totalTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("end_totalTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=4,Right=3,Bottom=4}.
        /// </summary>
        internal static System.Windows.Forms.Padding end_totalTextBox_Margin {
            get {
                object obj = ResourceManager.GetObject("end_totalTextBox.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool end_totalTextBox_Multiline {
            get {
                object obj = ResourceManager.GetObject("end_totalTextBox.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=207, Height=41}.
        /// </summary>
        internal static System.Drawing.Size end_totalTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("end_totalTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 24.
        /// </summary>
        internal static int end_totalTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("end_totalTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.HorizontalAlignment similar to Center.
        /// </summary>
        internal static System.Windows.Forms.HorizontalAlignment end_totalTextBox_TextAlign {
            get {
                object obj = ResourceManager.GetObject("end_totalTextBox.TextAlign", resourceCulture);
                return ((System.Windows.Forms.HorizontalAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=-3,Y=39}.
        /// </summary>
        internal static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=312, Height=59}.
        /// </summary>
        internal static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 32.
        /// </summary>
        internal static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدد طرقة البحث.
        /// </summary>
        internal static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font id_Font {
            get {
                object obj = ResourceManager.GetObject("id.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=473,Y=56}.
        /// </summary>
        internal static System.Drawing.Point id_Location {
            get {
                object obj = ResourceManager.GetObject("id.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=4,Right=3,Bottom=4}.
        /// </summary>
        internal static System.Windows.Forms.Padding id_Margin {
            get {
                object obj = ResourceManager.GetObject("id.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=208, Height=37}.
        /// </summary>
        internal static System.Drawing.Size id_Size {
            get {
                object obj = ResourceManager.GetObject("id.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 17.
        /// </summary>
        internal static int id_TabIndex {
            get {
                object obj = ResourceManager.GetObject("id.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font label1_Font {
            get {
                object obj = ResourceManager.GetObject("label1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=328,Y=58}.
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=117, Height=31}.
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 18.
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث برقم العميل.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool msg_AutoSize {
            get {
                object obj = ResourceManager.GetObject("msg.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font msg_Font {
            get {
                object obj = ResourceManager.GetObject("msg.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=134,Y=116}.
        /// </summary>
        internal static System.Drawing.Point msg_Location {
            get {
                object obj = ResourceManager.GetObject("msg.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=80, Height=31}.
        /// </summary>
        internal static System.Drawing.Size msg_Size {
            get {
                object obj = ResourceManager.GetObject("msg.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        internal static int msg_TabIndex {
            get {
                object obj = ResourceManager.GetObject("msg.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتائج البحث.
        /// </summary>
        internal static string msg_Text {
            get {
                return ResourceManager.GetString("msg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool name_AutoSize {
            get {
                object obj = ResourceManager.GetObject("name.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font name_Font {
            get {
                object obj = ResourceManager.GetObject("name.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=316,Y=58}.
        /// </summary>
        internal static System.Drawing.Point name_Location {
            get {
                object obj = ResourceManager.GetObject("name.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=31}.
        /// </summary>
        internal static System.Drawing.Size name_Size {
            get {
                object obj = ResourceManager.GetObject("name.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        internal static int name_TabIndex {
            get {
                object obj = ResourceManager.GetObject("name.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        internal static string name_Text {
            get {
                return ResourceManager.GetString("name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool searchbyid_AutoSize {
            get {
                object obj = ResourceManager.GetObject("searchbyid.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=24}.
        /// </summary>
        internal static System.Drawing.Point searchbyid_Location {
            get {
                object obj = ResourceManager.GetObject("searchbyid.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=142, Height=21}.
        /// </summary>
        internal static System.Drawing.Size searchbyid_Size {
            get {
                object obj = ResourceManager.GetObject("searchbyid.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int searchbyid_TabIndex {
            get {
                object obj = ResourceManager.GetObject("searchbyid.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث برقم الحساب.
        /// </summary>
        internal static string searchbyid_Text {
            get {
                return ResourceManager.GetString("searchbyid.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool searchbyname_AutoSize {
            get {
                object obj = ResourceManager.GetObject("searchbyname.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=200,Y=24}.
        /// </summary>
        internal static System.Drawing.Point searchbyname_Location {
            get {
                object obj = ResourceManager.GetObject("searchbyname.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=106, Height=21}.
        /// </summary>
        internal static System.Drawing.Size searchbyname_Size {
            get {
                object obj = ResourceManager.GetObject("searchbyname.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int searchbyname_TabIndex {
            get {
                object obj = ResourceManager.GetObject("searchbyname.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث بالاسم.
        /// </summary>
        internal static string searchbyname_Text {
            get {
                return ResourceManager.GetString("searchbyname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Simplified Arabic, Size=13, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font sname_Font {
            get {
                object obj = ResourceManager.GetObject("sname.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=451,Y=56}.
        /// </summary>
        internal static System.Drawing.Point sname_Location {
            get {
                object obj = ResourceManager.GetObject("sname.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=4,Right=3,Bottom=4}.
        /// </summary>
        internal static System.Windows.Forms.Padding sname_Margin {
            get {
                object obj = ResourceManager.GetObject("sname.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=248, Height=37}.
        /// </summary>
        internal static System.Drawing.Size sname_Size {
            get {
                object obj = ResourceManager.GetObject("sname.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 19.
        /// </summary>
        internal static int sname_TabIndex {
            get {
                object obj = ResourceManager.GetObject("sname.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton1_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton1.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color toolStripButton1_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("toolStripButton1.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=23, Height=33}.
        /// </summary>
        internal static System.Drawing.Size toolStripButton1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripButton1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعادة تحميل الصفحة.
        /// </summary>
        internal static string toolStripButton1_Text {
            get {
                return ResourceManager.GetString("toolStripButton1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton2_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color toolStripButton2_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("toolStripButton2.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=66, Height=33}.
        /// </summary>
        internal static System.Drawing.Size toolStripButton2_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripButton2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string toolStripButton2_Text {
            get {
                return ResourceManager.GetString("toolStripButton2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=36}.
        /// </summary>
        internal static System.Drawing.Size toolStripSeparator1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=36}.
        /// </summary>
        internal static System.Drawing.Size toolStripSeparator17_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator17.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=486,Y=24}.
        /// </summary>
        internal static System.Drawing.Point vw_customerTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("vw_customerTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=297,Y=23}.
        /// </summary>
        internal static System.Drawing.Point vwcustomerBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("vwcustomerBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
